import { Chess } from "https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm";
const game=new Chess(),boardEl=document.getElementById('board'),boardWrap=document.querySelector('.board-wrap'),home=document.getElementById('home'),gameScreen=document.getElementById('game'),turnText=document.getElementById('turnText'),statusEl=document.getElementById('status'),messageEl=document.getElementById('message'),movesEl=document.getElementById('moves'),resultModal=document.getElementById('resultModal'),resultTitle=document.getElementById('resultTitle'),resultReason=document.getElementById('resultReason'),resultIcon=document.getElementById('resultIcon');
let selected=null,orientation='w',modalShown=false,flipping=false,flipTimer=null,flipSwapTimer=null;const files=['a','b','c','d','e','f','g','h'],glyph={p:['♙','♟'],n:['♘','♞'],b:['♗','♝'],r:['♖','♜'],q:['♕','♛'],k:['♔','♚']};
function start(){game.reset();selected=null;orientation='w';modalShown=false;flipping=false;clearTimeout(flipTimer);clearTimeout(flipSwapTimer);boardWrap.classList.remove('flipping');boardWrap.querySelectorAll('.dust-particle').forEach(p=>p.remove());resultModal.classList.add('hidden');home.classList.add('hidden');gameScreen.classList.remove('hidden');render()}
function gameResult(){if(game.isCheckmate())return{title:`${game.turn()==='w'?'Black':'White'} wins`,reason:'by checkmate',icon:game.turn()==='w'?'♚':'♔'};if(game.isStalemate())return{title:'Draw',reason:'by stalemate',icon:'½'};if(game.isThreefoldRepetition())return{title:'Draw',reason:'by threefold repetition',icon:'½'};if(game.isDrawByFiftyMoves())return{title:'Draw',reason:'by the 50-move rule',icon:'½'};if(game.isInsufficientMaterial())return{title:'Draw',reason:'by insufficient material',icon:'½'};return null}
function showResult(r){if(!r||modalShown)return;modalShown=true;resultTitle.textContent=r.title;resultReason.textContent=r.reason;resultIcon.textContent=r.icon;resultModal.classList.remove('hidden')}
function makeDust(){boardWrap.querySelectorAll('.dust-particle').forEach(p=>p.remove());const edges=[['top',8],['top',19],['top',33],['top',51],['top',70],['top',88],['bottom',6],['bottom',23],['bottom',43],['bottom',63],['bottom',82],['bottom',96],['left',13],['left',31],['left',54],['left',76],['right',17],['right',39],['right',62],['right',84]];edges.forEach(([edge,pos],i)=>{const p=document.createElement('i');p.className='dust-particle';p.style[edge]=`${pos}%`;p.style.setProperty('--dx',`${edge==='left'?-(8+(i%4)*6):edge==='right'?(8+(i%4)*6):(i%2?6:-6)}px`);p.style.setProperty('--dy',`${edge==='top'?-(5+(i%3)*4):edge==='bottom'?(5+(i%3)*4):(i%2?5:-5)}px`);p.style.setProperty('--delay',`${.58+(i%5)*.016}s`);p.style.setProperty('--size',`${2+(i%3)}px`);boardWrap.appendChild(p)})}
function animateFlip(next){clearTimeout(flipTimer);clearTimeout(flipSwapTimer);boardWrap.classList.remove('flipping');void boardWrap.offsetWidth;makeDust();flipping=true;boardWrap.classList.add('flipping');flipSwapTimer=setTimeout(()=>{orientation=next;renderBoard()},450);flipTimer=setTimeout(()=>{flipping=false;boardWrap.classList.remove('flipping');boardWrap.querySelectorAll('.dust-particle').forEach(p=>p.remove());const r=gameResult();document.getElementById('resign').disabled=!!r;showResult(r)},950)}
function renderBoard(){boardEl.innerHTML='';const ranks=orientation==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8],fs=orientation==='w'?files:[...files].reverse(),legal=selected?game.moves({square:selected,verbose:true}):[];for(const rank of ranks)for(const file of fs){const sq=file+rank,piece=game.get(sq),b=document.createElement('button');b.className='square '+(((files.indexOf(file)+rank)%2)?'dark':'light');b.dataset.square=sq;if(sq===selected)b.classList.add('selected');const lm=legal.find(m=>m.to===sq);if(lm)b.classList.add(lm.captured?'capture':'legal');const coord=document.createElement('span');coord.className='coord';coord.textContent=sq;b.appendChild(coord);if(piece){const span=document.createElement('span');span.className='piece '+(piece.color==='w'?'white-piece':'black-piece');span.textContent=glyph[piece.type][piece.color==='w'?0:1];b.appendChild(span)}b.addEventListener('pointerdown',e=>{e.preventDefault();handleSquare(sq)});boardEl.appendChild(b)}if(game.inCheck()){let kingSq=null;for(const rank of ranks){for(const file of fs){const q=file+rank,p=game.get(q);if(p&&p.type==='k'&&p.color===game.turn()){kingSq=q;break}}if(kingSq)break}if(kingSq)boardEl.querySelector(`[data-square="${kingSq}"]`)?.classList.add('check')}}
function render(playFlip=false,next=null){renderBoard();const turn=game.turn()==='w'?'White':'Black',r=gameResult();turnText.textContent=r?'Game over':`${turn} to move`;statusEl.textContent=r?`${r.title} ${r.reason}`:game.inCheck()?`${turn} is in check`:`${turn} to move`;statusEl.className='status'+(r?' game-over':'');messageEl.textContent=r?'The game is finished. Start a new game to play again.':'Select a piece to see its legal moves.';document.getElementById('resign').disabled=!!r||flipping;renderMoves();if(playFlip)animateFlip(next);else showResult(r)}
function handleSquare(sq){if(game.isGameOver()||flipping)return;const piece=game.get(sq);if(selected){const move=game.moves({square:selected,verbose:true}).find(m=>m.to===sq);if(move){makeMove(selected,sq,move);return}if(piece&&piece.color===game.turn()){selected=sq;render();return}selected=null;render();return}if(piece&&piece.color===game.turn()){selected=sq;render()}}
function makeMove(from,to,move){let promotion;if(move.promotion){const answer=(prompt('Promote to: queen, rook, bishop, or knight','queen')||'queen').toLowerCase().trim();promotion=({queen:'q',rook:'r',bishop:'b',knight:'n'})[answer]||'q'}try{game.move({from,to,promotion});const next=game.turn()==='w'?'w':'b';selected=null;render(true,next)}catch(e){selected=null;render()}}
function resign(){if(game.isGameOver()||flipping)return;const resigning=game.turn()==='w'?'White':'Black',winner=resigning==='White'?'Black':'White';modalShown=true;resultTitle.textContent=`${winner} wins`;resultReason.textContent=`by resignation (${resigning} resigned)`;resultIcon.textContent=winner==='White'?'♔':'♚';turnText.textContent='Game over';statusEl.textContent=`${winner} wins by resignation`;statusEl.className='status game-over';messageEl.textContent='The game is finished. Start a new game to play again.';document.getElementById('resign').disabled=true;resultModal.classList.remove('hidden')}
function renderMoves(){movesEl.innerHTML='';const sans=game.history();for(let i=0;i<sans.length;i+=2){const li=document.createElement('li');li.textContent=`${i/2+1}. ${sans[i]}${sans[i+1]?'  '+sans[i+1]:''}`;movesEl.appendChild(li)}}
document.getElementById('newGame').addEventListener('click',start);document.getElementById('restart').addEventListener('click',start);document.getElementById('modalNewGame').addEventListener('click',start);document.getElementById('resign').addEventListener('click',resign);