import { Chess } from "https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm";
const ENGINE_URL="https://unpkg.com/stockfish@18.0.8/bin/stockfish-18-lite-single.js",DEPTH=18;
let engine=null,ready=false,busy=false,lastSignature="";
const $=id=>document.getElementById(id);
const classes={"Missed Win":{icon:"−",class:"missed-win"},"Miss":{icon:"×",class:"miss"},"Mistake":{icon:"?",class:"mistake"},"Interesting":{icon:"!?",class:"interesting"},"Inaccuracy":{icon:"?!",class:"inaccuracy"},"Book":{icon:"📚",class:"book"},"Good":{icon:"✓",class:"good"},"Excellent":{icon:"👍",class:"excellent"},"Best":{icon:"⭐",class:"best"},"Great":{icon:"!",class:"great"},"Brilliant":{icon:"!!",class:"brilliant"},"Blunder":{icon:"??",class:"blunder"}};
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
let engineResolve=null;
function initEngine(){if(engine)return;try{engine=new Worker(ENGINE_URL);engine.onmessage=e=>handleEngine(e.data);engine.onerror=e=>{console.warn("Stockfish review engine error",e);ready=false;busy=false;engine=null};engine.postMessage("uci")}catch(e){console.warn("Could not start Stockfish",e)}}
function handleEngine(line){if(typeof line!=="string")return;if(line==="uciok"){engine.postMessage("setoption name Threads value 1");engine.postMessage("isready");return}if(line==="readyok"){ready=true;return}if(line.startsWith("bestmove ")){const p=line.trim().split(/\s+/),best=p[1]||null;let score=null,mate=null;for(let i=0;i<p.length-1;i++){if(p[i]==="score"&&p[i+1]==="cp")score=Number(p[i+2]);if(p[i]==="score"&&p[i+1]==="mate")mate=Number(p[i+2])}const r=engineResolve;engineResolve=null;busy=false;if(r)r({best,score,mate})}}
async function ensureEngine(){initEngine();for(let i=0;i<100&&!ready;i++)await wait(100);return ready}
async function search(fen){if(!(await ensureEngine()))return null;while(busy)await wait(20);busy=true;return new Promise(resolve=>{engineResolve=resolve;engine.postMessage("ucinewgame");engine.postMessage("isready");const start=()=>{if(ready){engine.postMessage(`position fen ${fen}`);engine.postMessage(`go depth ${DEPTH}`)}else setTimeout(start,20)};start()})}
function getMoveSans(){return [...document.querySelectorAll("#moves .move-san")].map(x=>x.textContent.trim()).filter(Boolean)}
function replay(sans){const c=new Chess(),before=[];for(const san of sans){const fen=c.fen();let mv;try{mv=c.move(san)}catch{return null}before.push({fen,move:mv,san})}return {game:c,before}}
function cpScore(r,mover){if(!r)return null;if(r.mate!==null&&r.mate!==undefined){const n=Math.abs(r.mate);return r.mate>0?100000-n*1000:-100000+n*1000}if(r.score===null||r.score===undefined)return null;return mover==="w"?r.score:-r.score}
function ep(v){return v===null?.5:1/(1+Math.exp(-v/360))}
function material(c,color){const vals={p:100,n:320,b:330,r:500,q:900,k:0};let s=0;for(const row of c.board())for(const p of row)if(p)s+=(p.color===color?1:-1)*vals[p.type];return s}
function commonBook(sans){const p=sans.join(" "),prefixes=["e4 e5","e4 c5","e4 e6","e4 c6","e4 d5","d4 d5","d4 Nf6","d4 f5","c4 e5","c4 Nf6","Nf3 d5","Nf3 Nf6","e4 e5 Nf3 Nc6","e4 e5 Nf3 Nf6","e4 c5 Nf3 d6","e4 c5 Nf3 Nc6","d4 Nf6 c4 g6","d4 d5 c4 e6","c4 e5 Nc3 Nf6"];return prefixes.some(x=>p===x||p.startsWith(x+" "))&&sans.length<=12}
async function analyzeLatest(){const sans=getMoveSans();if(!sans.length){clearReview();return}const sig=sans.join("|");if(sig===lastSignature)return;const data=replay(sans);if(!data)return;const idx=sans.length-1,pre=new Chess();pre.load(data.before[idx].fen);const played=data.before[idx].move,post=new Chess();post.load(data.before[idx].fen);try{post.move(sans[idx])}catch{return}const mover=pre.turn();lastSignature=sig;const beforeEval=await search(pre.fen());const afterEval=await search(post.fen());const best=cpScore(beforeEval,mover),playedScore=cpScore(afterEval,mover);if(best===null||playedScore===null)return;const loss=Math.max(0,best-playedScore),beforeEP=ep(best),afterEP=ep(playedScore),epLoss=Math.max(0,beforeEP-afterEP),bestUci=beforeEval.best,playedUci=played.from+played.to+(played.promotion||""),isBest=bestUci===playedUci,sacrifice=material(post,mover)<material(pre,mover)-100;let label;if(commonBook(sans))label="Book";else if(isBest&&sacrifice&&playedScore>-150&&best<150)label="Brilliant";else if(best>=300&&playedScore<100)label=epLoss>=.20?"Missed Win":"Miss";else if(isBest&&loss<=5)label="Best";else if(isBest&&loss<=20)label="Excellent";else if(isBest&&best-playedScore>80)label="Great";else if(sacrifice&&loss<=80)label="Interesting";else if(loss<=20||epLoss<.02)label="Excellent";else if(loss<=50||epLoss<.05)label="Good";else if(loss<=100||epLoss<.10)label="Inaccuracy";else if(loss<=200||epLoss<.20)label="Mistake";else label="Blunder";const info=classes[label]||classes.Good;placeReviewBadge(played.to,info,label);updateEngineEval(playedScore);updateReviewList(label)}
function updateEngineEval(cp){const pawns=cp/100,clamped=Math.max(-5,Math.min(5,pawns)),pct=(clamped+5)/10*100,fill=$("evalFill"),marker=$("evalMarker"),info=$("evalInfo");if(fill)fill.style.height=`${100-pct}%`;if(marker)marker.style.top=`${pct}%`;if(info)info.textContent=`SF18 ${pawns>=0?"+":""}${pawns.toFixed(2)}`}
function placeReviewBadge(square,info,label){document.querySelectorAll(".review-square-badge").forEach(x=>x.remove());const el=document.querySelector(`#board [data-square="${square}"]`);if(!el)return;const b=document.createElement("span");b.className=`review-square-badge ${info.class}`;b.innerHTML=`<span class="review-icon">${info.icon}</span><span class="review-word">${label}</span>`;b.title=label;el.appendChild(b)}
function updateReviewList(label){document.querySelectorAll("#moves .move-badge").forEach(x=>x.remove());const row=[...document.querySelectorAll("#moves .move-row")].at(-1);if(row)row.dataset.classification=label}
function clearReview(){document.querySelectorAll(".review-square-badge").forEach(x=>x.remove());document.querySelectorAll("#moves .move-badge").forEach(x=>x.remove());lastSignature=""}
const observer=new MutationObserver(()=>{const sig=getMoveSans().join("|");if(sig!==lastSignature)setTimeout(analyzeLatest,120)});
function boot(){initEngine();const board=$("board"),moves=$("moves");if(!board||!moves)return;observer.observe(board,{childList:true,subtree:true});observer.observe(moves,{childList:true,subtree:true,characterData:true});setTimeout(analyzeLatest,700)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
window.addEventListener("beforeunload",()=>{try{engine?.terminate()}catch{}});
